.TH LTGCHECK "1" "Jul 2025" "ltgcheck VERSION" "User Command"
.SH NAME
.PP
ltgcheck \- Check document grammar using LanguageTool
.SH SYNOPSIS
.PP
.B ltgcheck
[\fIOPTIONS\fR]
[\fIFILE\fR]
.br
.B ltgcheck
.B  \-\-help
.SH DESCRIPTION
The program
.B ltgcheck
uses a server running LanguageTool to perform a grammar check on
plain text, open-document-format text files, and LaTeX files. The
output lists a file name and a line number for each error message that
LanguageTool generates, formatted so that the emacs
.B compile
command will show the text associated with each error. This command
reads the error messages and maps them to marks in the file, so that
a "go to next error" command will show the correct line in the file,
even addition lines have been inserted before that line. The command-line
argument
.I FILE
is the name of an input file.  If missing, standard input is assumed,
but a file is required for open-document-format text files.
.PP
For LaTeX files
.B ltgcheck
ignores comments, except for
.B ltgcheck
directives and emacs
.B LocalWords
comments, and removes LaTex commands. It will not process the argument of a
LaTeX command for section headings, commands that do not provide any text
(e.g.
.BR \eusepackage ),
and a some special cases such as
.BR \everb .
It will also not process the contents of some environments such as the
ones used to create equations as the text of these will in general should
not be checked for grammar errors.
.B ltgcheck
directives can also be placed in a LaTeX file, represented as stylized
comments. These can appear anywhere in a LaTeX file and affect subsequent
LaTeX commands and environments:
.TP
.BI %\ ltgcheck: \ NAME \ hide \ REPLACEMENT
.TQ
.BI %\ ltgcheck: \ NAME \ true \ REPLACEMENT
.TQ
.BI %\ ltgcheck: \ NAME \ show
.TQ
.BI %\ ltgcheck: \ NAME \ false
The argument
.I NAME
is the name of a LaTeX environment or single-argument command, and
must start with
.B \e
when the name refers to a command. The value
.BR hide \ or \ true
indicates that the contents of an environment or the argument of a
command will be replaced by
.IR REPLACEMENT ,
which should start and end with parenthesis or a bracket.  The value
.BR show \ or \ false
indicates that the the contents of an environment or the argument of a
command will be processed.  An ltgcheck directive will be ignored for
the commands
.BR \e" ,
\" "
.BR \e' ,
.BR \eH ,
.BR \eO ,
.BR \eo ,
.BR \e^ ,
.BR \e` ,
.BR \e~ ,
.BR \e\e ,
.BR \eeauthor ,
.BR \ecaption ,
.BR \edate ,
.BR \edocumentclass ,
.BR \efootnote ,
.BR \einclude ,
.BR \eincludeonly ,
.BR \eincludgraphics ,
.BR \einput ,
.BR \elabel ,
.BR \enewcommand ,
.BR \enewenvironment ,
.BR \epageref ,
.BR \eprovidecommand ,
.BR \eref ,
.BR \erenewcommand ,
.BR \erenewenvironment ,
.BR \eresizebox
.BR \etitle ,
and
.BR \eusepackage .
In addition, an
.B ltgcheck
directive will be ignored for the environments
.BR displaymath ,
.BR eqnarray ,
.BR eqnarray* ,
and
.BR equation ,
whose contents are replaced, and for
the
.B document
environment, whose contents are processed. For example,
.IP
.B \enewenvironment{code}{\ett}{}
.br
.B %\ ltgcheck:\ \ecode\ hide\ (code)
.IP
will create a LaTeX environment whose contents will be displayed using a
typewriter font, and that will be replaced with the string
.B (code)
when passed to LanguageTool so that LanguageTool will not generate
inappropriate warnings about spelling.  The replacement should include
parentheses to prevent LanguageTool from confusing the replacement with
part of a sentence.
.PP
For open-document-format files, most XML elements are ignored. A few
are replaced with line breaks.  Line breaks are also created after
anything that looks like the end of a sentence.
.PP
As a simple, straightforward program,
.B ltgcheck
is intended to handle most of a document provided the document is
mostly text. For LaTeX and open document format text files,
.B ltgcheck
assumes that the files are syntactically correct. Also, there are both
free and premium versions of LanguageTool.  The free version will
detect fewer errors than the premium version.
.B ltgcheck
has been tested using the Docker image meyay/languagetool. Visit
the URL
.PP
.B https://github.com/meyayl/docker-languagetool
.PP
for installation instructions (there is a docker-compose.yml file
there that can be easily used, with slight modifications (e.g.,
changing the user field).  The default URL used to connect to a
LanguageTool server is
.PP
.B http://localhost:8081/v2/check
.PP
but options can modify this or completely replace this URL.  The default
URL is the one appropriate for the Docker image listed above when run
on the same system as
.BR ltgcheck.
.SH OPTIONS
The options are
.TP
.B \-\-
This option indicates that no more options are present, and can
be used if a file name starts with
.BR \- .
.TP
.BI \-h \ HOST
.TQ
.BI \-\-host \ HOST
This option sets the host running the LanguageTool server.
.TP
.BI \-p \ PORT
.TQ
.BI \-\-port \ PORT
This option sets the TCP port used to connect to the LanguageTool server.
.TP
.BI \-\-https
This option changes the protocol in the URL used to connect to the
LanguageTool server to
.BR https .
.TP
.BI \-\-version \ VERSION
This option changes the version of LanguageTool as it appears in the
URL used to connect to the LanguageTool server. The default is
.BR v2 .
.TP
.BI \-\-url \ URL
This option provides the URL used to connect to the LanguageTool
server.  When present, any
.BR \-\-https ,
.BR \-\-host ,
.BR \-\-port ,
.B \-\-version
options are ignored.
.TP
.BI \-\-chapter \ CHAPTER
This option indicates that only chapter
.I CHAPTER
should be checked for errors, although all footnotes and captions will
also be checked.  Chapter 0 refers to any text preceding the first chapter
in the document.  This option applies to LaTeX files, but not files using
other formats. If neither
the
.B \-\-chapter
or the
.B \-\- notes
options are  provided, the full document will be checked.
.TP
.B \-\-ignoreLocalWords
This option indicates that words added to a document-specific dictionary
should be ignored during spelling checks.
.TP
.B \-\-listLocalWords
This option indicates that
.B ltgcheck
should list words added to a document-specific dictionary used the
emacs spelling software.  This is a LaTeX specific option.  The listed
words appear at the end of the input file on lines starting with either
"%LocalWords: " or "% LocalWords: ". LaTex eusepackage everb eH eO eo
.TP
.B \-\-notes
This option causes footnotes and captions to be checked for errors. If
The B \-\-chapter option is not provided, the only portion of the
document that will be checked are the footnotes and captions. If neither
the
.B \-\-chapter
or the
.B \-\- notes
options are provided, the full document will be checked.
.TP
.B \-\-odt
Indicates that the input file is an open document format text file. With
this option, standard input cannot be used. A file with the extension
changed to
.B .txt
will be created.  To avoid overwriting an existing file by accident,
include the
.B \-\-prompt
option so that
.B ltgcheck
will ask if the
.B .txt
file already exists.
.TP
.B \-\-print
Print the contents of a document after removing formatting directives.
Formatting directives will be removed for open document format text files
and LaTeX files. This option is mostly for debugging.
.TP
.B \-\-prompt
For open document format text files, ask before creating a file whose
extension is
.B .txt
if a file with that name exists.
.TP
.B \-\-raw
Print the content.xml portion of an open document
format text file.  This option cannot be used with standard input.
.TP
.B \-\-tex
Indicates that the input file, or standard input, is a LaTeX file.
.TP
.B \-\-itex
Indicates that the input file, or standard input, is a LaTeX file configured
to be included in another LaTex document.  Such files will typically be
missing a
.B \ebegin{document}
command.
.TP
.B \-\-text
Indicates that the input file, or standard input, is a plain text file.
.TP
.B \-?
.TQ
.B \-\-help
Print a "help" message.
.SH FILES
.B /usr/bin/ltgcheck
.B /usr/share/ltgcheck/ltgcheck.jar
.B /usr/share/doc/ltgcheck.copyright
.B /usr/share/doc/ltgcheck.changelog.gz
.B /usr/share/doc/ltgcheck.changelog.Bebian.gz
.SH AUTHOR
Written by Bill Zaumen
.SH COPYRIGHT
Copyright \(co 2025 Bill Zaumen.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
\"  LocalWords:  fIOPTIONS fR fIFILE br LaTeX emacs TT meyay yml TP
\"  LocalWords:  languagetool TQ TCP https url ignoreLocalWords odt
\"  LocalWords:  listLocalWords txt xml tex Zaumen GPLv GPL eeauthor
\"  LocalWords:  LTGCHECK ltgcheck LanguageTool ecaption edate einput
\"  LocalWords:  edocumentclass efootnote einclude eincludeonly eref
\"  LocalWords:  eincludgraphics elabel enewcommand enewenvironment
\"  LocalWords:  epageref eprovidecommand erenewcommand eresizebox
\"  LocalWords:  erenewenvironment etitle displaymath eqnarray ett
\"  LocalWords:  ecode itex ebegin
